MiniSpiir/Models/MiniSpiirDbContext.cs
using System.Data.Entity;

namespace MiniSpiir.Models
{
    public class MiniSpiirDbContext : DbContext
    {
        public DbSet<Posting> Postings { get; set; }
    }
}

MiniSpiir/Models/Posting.cs
using System;

namespace MiniSpiir.Models
{
    public class Posting
    {
        public int Id { get; set; }

        public DateTime Date { get; set; }

        public string Text { get; set; }

        public decimal Amount { get; set; }

        public string Category { get; set; }
    }
}

MiniSpiir/Controllers/Api/OverviewController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Http;
using MiniSpiir.Models;

namespace MiniSpiir.Controllers.Api
{
    public class OverviewController : ApiController
    {
        private readonly MiniSpiirDbContext db = new MiniSpiirDbContext();

        // GET api/overview
        public IEnumerable<OverviewCategory> Get()
        {
            return db.Postings.GroupBy(p => p.Category)
                     .Select(g => new OverviewCategory {Total = g.Sum(p => p.Amount), Name = g.Key})
                     .OrderByDescending(o => o.Total)
                     .ToList();
        }
    }

    public class OverviewCategory
    {
        public string Name { get; set; }
        public decimal Total { get; set; }
    }
}

MiniSpiir/Controllers/Api/PostingController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using MiniSpiir.Models;

namespace MiniSpiir.Controllers.Api
{
    public class PostingController : ApiController
    {
        private MiniSpiirDbContext db = new MiniSpiirDbContext();

        // GET api/PostingApi
        public IEnumerable<Posting> GetPostings()
        {
            return db.Postings.AsEnumerable();
        }

        // GET api/PostingApi/5
        public Posting GetPosting(int id)
        {
            Posting posting = db.Postings.Find(id);
            if (posting == null)
            {
                throw new HttpResponseException(Request.CreateResponse(HttpStatusCode.NotFound));
            }

            return posting;
        }

        // PUT api/PostingApi/5
        public HttpResponseMessage PutPosting(int id, Posting posting)
        {
            if (ModelState.IsValid && id == posting.Id)
            {
                db.Entry(posting).State = EntityState.Modified;

                try
                {
                    db.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    return Request.CreateResponse(HttpStatusCode.NotFound);
                }

                return Request.CreateResponse(HttpStatusCode.OK);
            }
            else
            {
                return Request.CreateResponse(HttpStatusCode.BadRequest);
            }
        }

        // POST api/PostingApi
        public HttpResponseMessage PostPosting(Posting posting)
        {
            if (ModelState.IsValid)
            {
                db.Postings.Add(posting);
                db.SaveChanges();

                HttpResponseMessage response = Request.CreateResponse(HttpStatusCode.Created, posting);
                response.Headers.Location = new Uri(Url.Link("DefaultApi", new { id = posting.Id }));
                return response;
            }
            else
            {
                return Request.CreateResponse(HttpStatusCode.BadRequest);
            }
        }

        // DELETE api/PostingApi/5
        public HttpResponseMessage DeletePosting(int id)
        {
            Posting posting = db.Postings.Find(id);
            if (posting == null)
            {
                return Request.CreateResponse(HttpStatusCode.NotFound);
            }

            db.Postings.Remove(posting);

            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                return Request.CreateResponse(HttpStatusCode.NotFound);
            }

            return Request.CreateResponse(HttpStatusCode.OK, posting);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

MiniSpiir/Controllers/DurandalController.cs
using System.Web.Mvc;

namespace MiniSpiir.Controllers {
  public class DurandalController : Controller {
    public ActionResult Index() {
      return View();
    }
  }
}

MiniSpiir/Controllers/OverviewController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using MiniSpiir.Models;

namespace MiniSpiir.Controllers
{
    public class OverviewController : Controller
    {
        private readonly MiniSpiirDbContext _miniSpiirDbContext;

        public OverviewController()
        {
            _miniSpiirDbContext = new MiniSpiirDbContext();
        }

        public ActionResult Index()
        {
            List<Posting> postings = _miniSpiirDbContext.Postings.ToList();

            var categories = postings.GroupBy(p => p.Category)
                                     .Select(g => new {y = g.Sum(p => p.Amount), name = g.Key})
                                     .OrderByDescending(o => o.y)
                                     .ToList();

            return View(new OverviewViewModel { ChartJson = new JavaScriptSerializer().Serialize(categories) });
        }
    }

    public class OverviewViewModel 
    {
        public string ChartJson { get; set; }
    }
}

MiniSpiir/Controllers/PostingController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using MiniSpiir.Models;

namespace MiniSpiir.Controllers
{
    public class PostingController : Controller
    {
        private readonly MiniSpiirDbContext _miniSpiirDbContext;

        public PostingController()
        {
            _miniSpiirDbContext = new MiniSpiirDbContext();
        }

        public ActionResult Index()
        {
            List<Posting> postings = _miniSpiirDbContext.Set<Posting>().OrderByDescending(p => p.Date).ToList();

            return View(postings);
        }

        public ActionResult Create(Posting posting)
        {
            if (!ModelState.IsValid)
            {
                TempData["Message"] = "Invalid posting!";
                return RedirectToAction("Index");
            }

            _miniSpiirDbContext.Postings.Add(posting);
            _miniSpiirDbContext.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

MiniSpiir/Views/Durandal/Index.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html>
    <head>
        <title>MiniSpiir</title>
        
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black" />
        <meta name="format-detection" content="telephone=no"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        
        <link rel="apple-touch-startup-image" href="~/Content/images/ios-startup-image-landscape.png" media="(orientation:landscape)" />
        <link rel="apple-touch-startup-image" href="~/Content/images/ios-startup-image-portrait.png" media="(orientation:portrait)" />
        <link rel="apple-touch-icon" href="~/Content/images/icon.png"/>
        
        @Styles.Render("~/Content/css")
        
        <script type="text/javascript">
            if (navigator.userAgent.match(/IEMobile\/10\.0/)) {
                var msViewportStyle = document.createElement("style");
                var mq = "@@-ms-viewport{width:auto!important}";
                msViewportStyle.appendChild(document.createTextNode(mq));
                document.getElementsByTagName("head")[0].appendChild(msViewportStyle);
            }
        </script>
    </head>
    <body>
        <div id="applicationHost">
            @Html.Partial("_splash")
        </div>
        
        @Scripts.Render("~/scripts/vendor")
        
        @if(HttpContext.Current.IsDebuggingEnabled) {
            <script type="text/javascript" src="~/App/durandal/amd/require.js" data-main="@Url.Content("~/App/main")"></script>
        } else {
            <script type="text/javascript" src="~/App/main-built.js"></script>
        }
    </body>
</html>

MiniSpiir/Views/Durandal/_splash.cshtml
<div class="splash">
    <div class="message">
        Durandal Starter Kit
    </div>
    <i class="icon-spinner icon-2x icon-spin active"></i>
</div>

MiniSpiir/Views/Overview/Index.cshtml
@model MiniSpiir.Controllers.OverviewViewModel

@{
    ViewBag.Title = "Overblik";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Overblik</h1>

<div id="chart"></div>

<script>
    $(function() {
        function getCategoryBarChartOptions(options) {
            options = $.extend({
                data: [],
                onclick: function() {
                },
                animate: false,
                color: '#ff6d1e',
                renderTo: null
            }, options);

            var categories = options.data.map(function(p) { return p.name; });

            var chartOptions = {
                chart: {
                    defaultSeriesType: 'bar',
                    marginLeft: 10,
                    marginRight: 40,
                    renderTo: options.renderTo,
                    height: options.data.length * 45 + 20,
                    margin: [0, 20, 20, 60],
                    style: {
                        fontFamily: 'MuseoSans, sans-serif'
                    }
                },
                title: {
                    text: null
                },
                xAxis: {
                    categories: categories,
                    tickInterval: 1,
                    maxPadding: 0.1,
                    minPadding: 0.1,
                    labels: {
                        align: 'left',
                        y: -14,
                        x: 0,
                        style: { color: '#3f3f3f' }
                    },
                    lineColor: '#fff',
                    tickWidth: 0
                },
                yAxis: {
                    min: 0,
                    title: { text: null },
                    gridLineColor: '#eee'
                },
                plotOptions: {
                    series: {
                        animation: options.animate
                    },
                    bar: {
                        dataLabels: {
                            enabled: true,
                            formatter: function() {
                                if (this.y === 0)
                                    return '';


                                return this.y + ' kr.';
                            },
                            x: 2,
                            y: Highcharts.Renderer === Highcharts.VMLRenderer ? 8 : 5,
                            style: { fontSize: '14px', color: '#3f3f3f' }
                        },
                        pointWidth: 20
                    }
                },
                series: [{
                    data: options.data,
                    color: options.color
                }],
                credits: { enabled: false },
                legend: { enabled: false },
            };

            return chartOptions;
        }

        var chartData = @Html.Raw(Model.ChartJson);
        var chart = new Highcharts.Chart(getCategoryBarChartOptions({
            renderTo: 'chart',
            data: chartData
        }));
    });
</script>

MiniSpiir/Views/Posting/Index.cshtml
@using MiniSpiir.Models
@model IEnumerable<MiniSpiir.Models.Posting>
    
@{
    ViewBag.Title = "Poster";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Poster</h1>

@if (TempData.ContainsKey("Message"))
{
    <p>@TempData["Message"]</p>
    
}

<table class="table">
    @foreach (Posting posting in Model)
    {
        <tr>
            <td class="date">@posting.Date.ToShortDateString()</td>
            <td>@posting.Text</td>
            <td>@posting.Category</td>
            <td class="amount">@posting.Amount</td>
        </tr>
    }
</table>

<h2>Opret post</h2>

@using (Html.BeginForm("Create", "Posting"))
{
    <input name="date" type="date" />
    <input name="text" type="text"  placeholder="Tekst" />
    <input name="amount" type="text" placeholder="Beløb" />
    <select name="category">        
        <option>Dagligvarer</option>
        <option>Tøj</option>
        <option>Transport</option>
        <option>Konferencer</option>
    </select>
    <button type="submit" class="btn btn-primary">Opret</button>
}

MiniSpiir/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>@ViewBag.Title</title>
    <script src="@Url.Content("~/Scripts/jquery.js")"> </script>
    <script src="@Url.Content("~/Scripts/highcharts.js")"> </script>
    @Styles.Render("~/Content/minispiir")
</head>
<body>
    <div class="navbar">
        <div class="navbar-inner">
            <a class="brand">
                <span>MiniSpiir</span>
            </a>
            <ul class="nav">
                <li>@Html.ActionLink("Overblik", "Index", "Overview")</li>
                <li>@Html.ActionLink("Poster", "Index", "Posting")</li>
            </ul>
        </div>
    </div>
    <div class="container-fluid">
        @RenderBody()
    </div>
</body>
</html>